from GameStructure import GameStructure
from DeepQNeuralBrain import DeepQNeuralBrain


STARTING_ROAD_WIDTH = 10
ENDING_ROAD_WIDTH = 25
NUM_ADVANCES_LEVEL_COMPLETE = 2000
DISPLAY_RATE = 2.0
RANDOM_OBSTACLE_PROBABILITY = .1
MAX_NUMBER_DISPLAY_ROAD_STATES = 3
MAX_NUMBER_ROAD_STATES = 6
MAX_HISTORY = 50
FAST_MODE = True
SAFE_REWARD = 1
CRASH_REWARD = -1
ADVANCES_LEARNING_INTERVAL = 4
DISCOUNT = 0.9
GAMMA = 0.9
NUMBER_ACTIONS = 3
STEP_SIZE = 0.2
DEEP_Q_TRAINING_INTERVAL = 1000
RANDOM_MOVE_PROBABILITY = .001
NUMBER_ROAD_SECTIONS_IN_Q_VALUES = 3


def main():
    game = GameStructure(STARTING_ROAD_WIDTH, ENDING_ROAD_WIDTH, NUM_ADVANCES_LEVEL_COMPLETE, \
        DISPLAY_RATE, RANDOM_OBSTACLE_PROBABILITY, MAX_NUMBER_DISPLAY_ROAD_STATES, \
        MAX_NUMBER_ROAD_STATES, ADVANCES_LEARNING_INTERVAL, MAX_HISTORY, FAST_MODE)

    deep_q_neural_brain = DeepQNeuralBrain(SAFE_REWARD, CRASH_REWARD, ADVANCES_LEARNING_INTERVAL, DISCOUNT, \
        GAMMA, NUMBER_ACTIONS, STEP_SIZE, DEEP_Q_TRAINING_INTERVAL, RANDOM_MOVE_PROBABILITY,
        NUMBER_ROAD_SECTIONS_IN_Q_VALUES)

    game.start(deep_q_neural_brain)


if __name__ == "__main__":
    main()
